MODULE_PATH_FIELD_NAME = "modulePath"
CLASS_FIELD_NAME = "class"
CLASS_PARAMETERS_FIELD_NAME = "classParameters"
MODEL_FIELD_NAME = "modelName"
FINISHED_FIELD_NAME = "finished"
DESCRIPTION_FIELD_NAME = "description"

HTTP_STATUS_CODE_SUCCESS = 200
HTTP_STATUS_CODE_SUCCESS_CREATED = 201
HTTP_STATUS_CODE_CONFLICT = 409
HTTP_STATUS_CODE_NOT_ACCEPTABLE = 406
GET_METHOD_NAME = "GET"

DEFAULT_MODEL_HOST_IP = "DEFAULT_MODEL_HOST_IP"
DEFAULT_MODEL_HOST_PORT = "DEFAULT_MODEL_HOST_PORT"

MODELS_VOLUME_PATH = "MODELS_VOLUME_PATH"

DATABASE_URL = "DATABASE_URL"
DATABASE_PORT = "DATABASE_PORT"
DATABASE_NAME = "DATABASE_NAME"
DATABASE_REPLICA_SET = "DATABASE_REPLICA_SET"

ID_FIELD_NAME = "_id"
METADATA_DOCUMENT_ID = 0

MESSAGE_RESULT = "result"

FUNCTION_PARAMETERS_NAME = "classParameters"
EXCEPTION_FIELD_NAME = "exception"

MICROSERVICE_URI_GET = "/api/learningOrchestra/v1/model/default/"
MICROSERVICE_URI_GET_PARAMS = "?query={}&limit=20&skip=0"

FIRST_ARGUMENT = 0
