class Constants:
    DEFAULT_MODEL_HOST_IP = ''
    DEFAULT_MODEL_HOST_PORT = ''

    DATABASE_URL = "DATABASE_URL"
    DATABASE_PORT = "DATABASE_PORT"
    DATABASE_NAME = "DATABASE_NAME"
    DATABASE_REPLICA_SET = "DATABASE_REPLICA_SET"

    MICROSERVICE_IP = "MICROSERVICE_IP"
    MICROSERVICE_PORT = "MICROSERVICE_PORT"

    MESSAGE_RESULT = "result"
    DELETED_MESSAGE = "deleted observer"

    API_PATH = "/api/learningOrchestra/v1"

    HTTP_STATUS_CODE_SUCCESS_CREATED = 201
    HTTP_STATUS_CODE_SUCCESS_FULFIlLED = 200
    HTTP_STATUS_CODE_BAD_REQUEST = 400
    HTTP_STATUS_CODE_CONFLICT = 409
    HTTP_STATUS_CODE_NOT_ACCEPTABLE = 406

    REQUEST_JSON_OBSERVE_TYPE = 'observe_type'
    REQUEST_JSON_TIMEOUT = 'timeout'
    REQUEST_JSON_FILENAME = 'filename'

    MESSAGE_RESPONSE_OBSERVER = "observer index"
    MESSAGE_RESPONSE_DATABASE = "database name"
    MESSAGE_RESPONSE_FILENAME = "collection name"
    MESSAGE_RESPONSE_QUERY = "query parameter"
    MESSAGE_RESPONSE_INVALID = "invalid"

    MICROSERVICE_URI_PATH = "/observer"