class Constants:
    DEFAULT_MODEL_HOST_IP = ''
    DEFAULT_MODEL_HOST_PORT = ''

    DATABASE_URL = "DATABASE_URL"
    DATABASE_PORT = "DATABASE_PORT"
    DATABASE_NAME = "DATABASE_NAME"
    DATABASE_REPLICA_SET = "DATABASE_REPLICA_SET"

    MICROSERVICE_IP = "MICROSERVICE_IP"
    MICROSERVICE_PORT = "MICROSERVICE_PORT"

    MESSAGE_RESULT = "result"
    DELETED_MESSAGE = "deleted observer"

    HTTP_STATUS_CODE_SUCCESS_CREATED = 201
    HTTP_STATUS_CODE_SUCCESS_FULFIlLED = 200
    HTTP_STATUS_CODE_BAD_REQUEST = 400
    HTTP_STATUS_CODE_CONFLICT = 409
    HTTP_STATUS_CODE_NOT_ACCEPTABLE = 406

    MESSAGE_RESPONSE_OBSERVER = "observer name"
    MESSAGE_RESPONSE_DATABASE = "database name"
    MESSAGE_RESPONSE_NOT_FOUND = " not found"