class Constants:
    HTTP_STATUS_CODE_SUCCESS = 200
    HTTP_STATUS_CODE_SUCCESS_CREATED = 201
    HTTP_STATUS_CODE_NOT_ACCEPTABLE = 406
    HTTP_STATUS_CODE_CONFLICT = 409

    DATABASE_API_HOST = "DATABASE_API_HOST"
    DATABASE_API_PORT = "DATABASE_API_PORT"

    MESSAGE_RESULT = "result"

    DATABASE_URL = "DATABASE_URL"
    DATABASE_PORT = "DATABASE_PORT"
    DATABASE_NAME = "DATABASE_NAME"
    DATABASE_REPLICA_SET = "DATABASE_REPLICA_SET"

    FILENAME_FIELD_NAME = "datasetName"
    URL_FIELD_NAME = "datasetURI"
    TYPE_FIELD_NAME = "type"
    DATASET_TYPE = "dataset/default"

    FIRST_ARGUMENT = 0

    MESSAGE_INVALID_URL = "invalid url"
    MESSAGE_DUPLICATE_FILE = "duplicate file"
    MESSAGE_DELETED_FILE = "deleted file"


    MICROSERVICE_URI_GET = "/api/learningOrchestra/v1/dataset/"
    MICROSERVICE_URI_GET_PARAMS = "?query={}&limit=10&skip=0"
    MICROSERVICE_URI_PATH = "/files"

    FINISHED = "finished"
    ROW_ID = "_id"
    METADATA_ROW_ID = 0

    LIMIT_PARAM_NAME = "limit"
    LIMIT_PARAM_MAX = 100
    LIMIT_DEFAULT_VALUE = 20

    SKIP_PARAM_NAME = "skip"
    SKIP_PARAM_MIN = 0
    SKIP_DEFAULT_VALUE = 0

    QUERY_PARAM_NAME = "query"
    QUERY_DEFAULT_VALUE = {}